package com.oagp.controller;

import com.google.genai.Client;
import com.oagp.model.AITier;
import com.oagp.model.GenerativeAIService;
import com.oagp.repository.ScanRepository;
import com.oagp.repository.ViolationNodeRepository;
import com.oagp.repository.ViolationRepository;
import com.oagp.service.JsonService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/ai")
public class AIController {

    private final Map<String, GenerativeAIService> aiServices;
    private final JsonService jsonService;

    private final ScanRepository scanRepository;
    private final ViolationRepository violationRepository;
    private final ViolationNodeRepository violationNodeRepository;

    @Autowired
    public AIController(Map<String, GenerativeAIService> aiServices,
                        JsonService jsonService,
                        ScanRepository scanRepository,
                        ViolationRepository violationRepository,
                        ViolationNodeRepository violationNodeRepository) {
        this.aiServices = aiServices;
        this.jsonService = jsonService;

        this.scanRepository = scanRepository;
        this.violationRepository = violationRepository;
        this.violationNodeRepository = violationNodeRepository;
    }

    @GetMapping("/{provider}/{tier}")
    public String ask(@PathVariable String provider,
                      @PathVariable AITier tier,
                      @RequestParam String prompt) {
        var service = aiServices.get(provider.toLowerCase());

        if (service == null) {
            throw new IllegalArgumentException(
                    "Invalid provider: " + provider + ". Use 'gemini' or 'openai'."
            );
        }

        return service.ask(prompt, tier);
    }

    @GetMapping()
    @RequestMapping("/evaluate")
    public String evaluate(@PathVariable Long scanId) {

        var scan = scanRepository.findById(scanId);
        var scanJson = "";
        try {
            scanJson = jsonService.toJson(scan);
        } catch (Exception e) {
            return e.getMessage();
        }

        var prompt = "You are an accessibility expert and technical communicator.\n" +
                "\n" +
                "Your job is to analyze accessibility testing results generated by axe-core and explain them in simple, plain English for developers with mixed experience levels.\n" +
                "\n" +
                "IMPORTANT:\n" +
                "- Do NOT use technical jargon unless you explain it\n" +
                "- Keep explanations short and clear\n" +
                "- Focus on what matters and what to fix first\n" +
                "- Be practical and actionable\n" +
                "\n" +
                "-------------------------------------\n" +
                "\n" +
                "INPUT:\n" +
                "You will receive JSON output from an accessibility testing engine (axe-core), which may include:\n" +
                "- violations (confirmed issues)\n" +
                "- incomplete (needs manual review)\n" +
                "- passes (ignore unless relevant)\n" +
                "\n" +
                "-------------------------------------\n" +
                "\n" +
                "TASK:\n" +
                "\n" +
                "1. SUMMARY (High-level overview)\n" +
                "- How many issues were found?\n" +
                "- Is this a serious problem or minor?\n" +
                "- One sentence overall assessment\n" +
                "\n" +
                "2. KEY ISSUES (Top problems only)\n" +
                "For each important issue:\n" +
                "- What is the problem (plain English)?\n" +
                "- Why it matters (impact on users)\n" +
                "- Example of who is affected (e.g. screen reader users)\n" +
                "\n" +
                "3. ACTION STEPS (Most important section)\n" +
                "Provide a clear list of fixes:\n" +
                "- Use bullet points\n" +
                "- Each step must be simple and direct\n" +
                "- Prioritise high-impact fixes first\n" +
                "\n" +
                "4. SIMPLE EXPLANATION\n" +
                "Explain like you're talking to a junior developer:\n" +
                "- What accessibility means in this context\n" +
                "- Why these issues should not be ignored\n" +
                "\n" +
                "5. OPTIONAL: QUICK WINS\n" +
                "- List 2–3 easy fixes that give the biggest improvement\n" +
                "\n" +
                "-------------------------------------\n" +
                "\n" +
                "RULES:\n" +
                "- Be concise but helpful\n" +
                "- No long paragraphs\n" +
                "- Prefer bullet points\n" +
                "- No raw WCAG codes without explanation\n" +
                "- Translate technical errors into human language\n" +
                "\n" +
                "-------------------------------------\n" +
                "\n" +
                "DATA:\n" + scanJson;

        return "";//aiService.ask(prompt);
    }
}
